# fly.toml app configuration file generated for apitest2 on 2025-08-26T10:42:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apitest2'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
